# Generated by Django 4.2.9 on 2026-10-03 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='物资编号')),
                ('name', models.CharField(max_length=200, verbose_name='物资名称')),
                ('case_type', models.CharField(choices=[('criminal', '刑事案件'), ('administrative', '行政案件'), ('other', '其他案件')], max_length=20, verbose_name='案件类型')),
                ('case_no', models.CharField(blank=True, max_length=100, verbose_name='案件编号')),
                ('intake_date', models.DateField(verbose_name='入库日期')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='存放位置')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在管')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_items', to='warehouse.category', verbose_name='物资品类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custody_items', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('goods', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_items', to='warehouse.goods', verbose_name='关联库存货物')),
            ],
            options={
                'verbose_name': '保管物资',
                'verbose_name_plural': '保管物资',
                'db_table': 'wh_custody_item',
                'ordering': ['-intake_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('criminal', '刑事案件'), ('administrative', '行政案件'), ('other', '其他案件')], max_length=20, verbose_name='案件类型')),
                ('retention_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='保管年限')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='是否永久保管')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('status', models.CharField(choices=[('active', '现行有效'), ('superseded', '已被新版替代')], default='active', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='规则说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retention_rules', to='warehouse.category', verbose_name='适用品类（空为通用规则）')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retention_rules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successors', to='warehouse.retentionrule', verbose_name='替代的上一版本')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='warehouse.retentionrule', verbose_name='替代为本版本的新版')),
            ],
            options={
                'verbose_name': '保管期限规则',
                'verbose_name_plural': '保管期限规则',
                'db_table': 'wh_retention_rule',
                'ordering': ['case_type', 'category_id', '-effective_date', '-version'],
                'unique_together': {('case_type', 'category', 'effective_date', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DisposalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('reason', models.TextField(blank=True, verbose_name='申请理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('decision_remark', models.TextField(blank=True, verbose_name='审批意见')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_disposal_requests', to=settings.AUTH_USER_MODEL, verbose_name='审批主管')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_requests', to='warehouse.custodyitem', verbose_name='保管物资')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '销毁处置申请',
                'verbose_name_plural': '销毁处置申请',
                'db_table': 'wh_disposal_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisposalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('as_of_date', models.DateField(verbose_name='计算基准日')),
                ('original_due_date', models.DateField(blank=True, null=True, verbose_name='原始到期日')),
                ('target_due_date', models.DateField(blank=True, null=True, verbose_name='延期后到期日（暂停计日前）')),
                ('projected_due_date', models.DateField(blank=True, null=True, verbose_name='预计最终到期日')),
                ('suspension_days', models.PositiveIntegerField(default=0, verbose_name='暂停顺延天数')),
                ('extension_days', models.PositiveIntegerField(default=0, verbose_name='累计延期天数')),
                ('indefinite_hold', models.BooleanField(default=False, verbose_name='存在未解除冻结/调查')),
                ('state', models.CharField(choices=[('permanent', '永久保管'), ('normal', '正常保管中'), ('suspended', '冻结/调查暂停中'), ('tolled', '暂停顺延中'), ('extended', '批准延期中'), ('eligible', '可进入销毁流程')], max_length=20, verbose_name='处置状态')),
                ('eligible_for_disposal', models.BooleanField(default=False, verbose_name='是否可进入销毁流程')),
                ('retained_reasons', models.JSONField(default=list, verbose_name='仍需保管的原因')),
                ('timeline', models.JSONField(default=list, verbose_name='期限计算时间线')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='warehouse.custodyitem', verbose_name='保管物资')),
                ('rule_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='warehouse.retentionrule', verbose_name='依据规则版本')),
            ],
            options={
                'verbose_name': '处置计划',
                'verbose_name_plural': '处置计划',
                'db_table': 'wh_disposal_plan',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='custodyitem',
            name='rule_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_items', to='warehouse.retentionrule', verbose_name='入库时适用规则版本'),
        ),
        migrations.CreateModel(
            name='CustodyHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_type', models.CharField(choices=[('legal_freeze', '法律冻结'), ('investigation', '未结调查')], max_length=20, verbose_name='暂停类型')),
                ('reference_no', models.CharField(blank=True, max_length=100, verbose_name='文书/案号')),
                ('authority', models.CharField(max_length=200, verbose_name='决定机关/办案单位')),
                ('reason', models.TextField(blank=True, verbose_name='暂停事由')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='解除日期')),
                ('lifted_at', models.DateTimeField(blank=True, null=True, verbose_name='解除时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_holds', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holds', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='warehouse.custodyitem', verbose_name='保管物资')),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_holds', to=settings.AUTH_USER_MODEL, verbose_name='解除人')),
            ],
            options={
                'verbose_name': '期限暂停记录',
                'verbose_name_plural': '期限暂停记录',
                'db_table': 'wh_custody_hold',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField(verbose_name='第几次延期')),
                ('base_due_date', models.DateField(verbose_name='批准时认定的到期日')),
                ('new_due_date', models.DateField(verbose_name='延期后到期日')),
                ('extension_days', models.PositiveIntegerField(verbose_name='延期天数')),
                ('reason', models.TextField(verbose_name='延期理由')),
                ('approved_at', models.DateTimeField(verbose_name='批准时间')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_extensions', to=settings.AUTH_USER_MODEL, verbose_name='批准主管')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_extensions', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='warehouse.custodyitem', verbose_name='保管物资')),
            ],
            options={
                'verbose_name': '保管延期批准',
                'verbose_name_plural': '保管延期批准',
                'db_table': 'wh_retention_extension',
                'ordering': ['item_id', 'seq'],
                'unique_together': {('item', 'seq')},
            },
        ),
    ]
