# Generated by Django 4.2.9 on 2026-10-03 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('criminal', '刑事案件'), ('civil', '民事案件'), ('administrative', '行政案件'), ('other', '其他案件')], max_length=20, verbose_name='案件类型')),
                ('retention_months', models.PositiveIntegerField(verbose_name='保管月数')),
                ('effective_from', models.DateField(verbose_name='生效日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_rules', to='warehouse.category', verbose_name='物资品类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retention_rules', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '保管期限规则',
                'verbose_name_plural': '保管期限规则',
                'db_table': 'rt_rule',
                'ordering': ['case_type', 'category', '-effective_from'],
                'unique_together': {('case_type', 'category', 'effective_from')},
            },
        ),
        migrations.CreateModel(
            name='RetentionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('criminal', '刑事案件'), ('civil', '民事案件'), ('administrative', '行政案件'), ('other', '其他案件')], max_length=20, verbose_name='案件类型')),
                ('anchor_date', models.DateField(verbose_name='起算日期')),
                ('original_due_date', models.DateField(verbose_name='原到期日')),
                ('current_due_date', models.DateField(verbose_name='当前到期日')),
                ('status', models.CharField(choices=[('in_custody', '保管中'), ('disposed', '已处置')], default='in_custody', max_length=20, verbose_name='状态')),
                ('disposed_at', models.DateTimeField(blank=True, null=True, verbose_name='处置时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retention_records', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('goods', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_record', to='warehouse.goods', verbose_name='货物')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='retention.retentionrule', verbose_name='适用规则')),
            ],
            options={
                'verbose_name': '保管期限记录',
                'verbose_name_plural': '保管期限记录',
                'db_table': 'rt_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_type', models.CharField(choices=[('legal_freeze', '法律冻结'), ('investigation', '未结调查'), ('extension', '批准延期')], max_length=20, verbose_name='措施类型')),
                ('reason', models.TextField(verbose_name='事由')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='解除日期')),
                ('extended_due_date', models.DateField(blank=True, null=True, verbose_name='延期后到期日')),
                ('release_reason', models.CharField(blank=True, max_length=200, verbose_name='解除说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登记时间')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_retention_holds', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retention_holds', to=settings.AUTH_USER_MODEL, verbose_name='登记人')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='retention.retentionrecord', verbose_name='保管记录')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_retention_holds', to=settings.AUTH_USER_MODEL, verbose_name='解除人')),
            ],
            options={
                'verbose_name': '保管措施',
                'verbose_name_plural': '保管措施',
                'db_table': 'rt_hold',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', '建档'), ('hold_placed', '措施登记'), ('hold_released', '措施解除'), ('plan_created', '计划生成'), ('plan_approved', '计划批准'), ('plan_executed', '计划执行'), ('plan_cancelled', '计划取消')], max_length=20, verbose_name='事件类型')),
                ('detail', models.JSONField(default=dict, verbose_name='事件详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_events', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='retention.retentionrecord', verbose_name='保管记录')),
            ],
            options={
                'verbose_name': '保管期限事件',
                'verbose_name_plural': '保管期限事件',
                'db_table': 'rt_event',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisposalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='计划处置日期')),
                ('method', models.CharField(choices=[('destruction', '销毁'), ('transfer', '移交')], default='destruction', max_length=20, verbose_name='处置方式')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已批准'), ('executed', '已执行'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('cancel_reason', models.CharField(blank=True, max_length=200, verbose_name='取消原因')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='批准时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_disposal_plans', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_disposal_plans', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_disposal_plans', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_plans', to='retention.retentionrecord', verbose_name='保管记录')),
            ],
            options={
                'verbose_name': '处置计划',
                'verbose_name_plural': '处置计划',
                'db_table': 'rt_disposal_plan',
                'ordering': ['-created_at'],
            },
        ),
    ]
